name: Flutter Integration Tests
on:
  push:
    branches:
      - main
jobs:
  Flutter_Tests:
    name: Build and test
    runs-on: macos-latest
    steps:
      - name: Get Repository
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Run Flutter Pub Get
        run: flutter pub get

      - name: Run Unit tests
        run: flutter test test/unit

      - name: Run Widget tests
        run: flutter test test/widget
      
      - name: Run Android integration tests
        run: ./integration_android.sh

      - name: Run iOS integration tests
        run: ./integration_ios.sh

      - name: Clean up keychain and provisioning profile
        if: ${{ always() }}
        run: |
          security delete-keychain $RUNNER_TEMP/app-signing.keychain-db
          rm ~/Library/MobileDevice/Provisioning\ Profiles/build_pp.mobileprovision